# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='divisa',
            field=models.CharField(default='-', max_length=5),
        ),
        migrations.AlterField(
            model_name='producto',
            name='familia',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='producto',
            name='linea',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='producto',
            name='marca',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='modelo',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_pub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidad',
            field=models.CharField(default='-', max_length=5),
        ),
    ]
