# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 20:54
from __future__ import unicode_literals

from django.db import migrations, models
import excel.models


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0002_auto_20170615_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=excel.models.upload_location, width_field='width_field'),
        ),
        migrations.AddField(
            model_name='producto',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
    ]
