# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0003_auto_20170615_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad', models.CharField(max_length=10)),
            ],
        ),
    ]
