# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 21:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0004_unidad'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Unidad',
            new_name='Unidade',
        ),
    ]
