# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0007_auto_20170615_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='familia',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidad',
            field=models.CharField(default='-', max_length=5),
        ),
        migrations.DeleteModel(
            name='Familia',
        ),
        migrations.DeleteModel(
            name='Unidade',
        ),
    ]
