# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0002_auto_20170518_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='apellido',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
