# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 17:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0003_mensaje_apellido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensaje',
            old_name='tema',
            new_name='Asunto',
        ),
    ]
