# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 17:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0004_auto_20170519_1020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensaje',
            old_name='Asunto',
            new_name='asunto',
        ),
    ]
