# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0004_auto_20170512_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='so',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
