# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 17:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0005_auto_20170519_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='apellido',
        ),
    ]
