# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0006_remove_mensaje_apellido'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clasificacion',
            new_name='Categoria',
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='clasificacion',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='equipo',
            old_name='clasificacion',
            new_name='categoria',
        ),
        migrations.AddField(
            model_name='equipo',
            name='so',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
