# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import start.models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0007_auto_20170519_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slideshow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
                ('imagen', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=start.models.upload_location, width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='start.Equipo')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
